# Generated by Django 4.2.2 on 2023-07-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='company')),
                ('call_us', models.CharField(blank=True, max_length=25, null=True)),
                ('email_us', models.CharField(blank=True, max_length=25, null=True)),
                ('subtitle', models.TextField(blank=True, max_length=200, null=True)),
                ('email', models.TextField(blank=True, max_length=200, null=True)),
                ('phones', models.TextField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('insta_link', models.URLField(blank=True, null=True)),
                ('tiktok_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('android_store', models.URLField(blank=True, null=True)),
                ('apple_store', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
