# Generated by Django 4.2.2 on 2023-07-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_flag'),
        ('products', '0005_product_video'),
    ]

    operations = [
    ]
